QUESTIONS = [

    # =========================================================
    # OPENNESS — 5 sub-dimensions × 5 questions = 25
    # =========================================================

    # --- Openness / Curiosity ---
    {
        "id": "OC1",
        "trait": "Openness",
        "sub_dimension": "Curiosity",
        "scenario": "You spot a documentary on a topic you know nothing about. What do you do?",
        "option_A": "Watch it fully and look up more afterward.",
        "option_B": "Watch part of it to see if it grabs me.",
        "option_C": "Bookmark it but rarely get around to watching it.",
        "option_D": "Skip it — I prefer things I already enjoy.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OC2",
        "trait": "Openness",
        "sub_dimension": "Curiosity",
        "scenario": "A coworker mentions an unusual historical fact you've never heard before. How do you respond?",
        "option_A": "Get drawn into the conversation and research it yourself later.",
        "option_B": "Ask one follow-up question out of genuine interest.",
        "option_C": "Acknowledge it briefly without pursuing it further.",
        "option_D": "Nod and move on — it doesn't seem relevant to anything.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OC3",
        "trait": "Openness",
        "sub_dimension": "Curiosity",
        "scenario": "You discover an unmarked trail while hiking. What is your instinct?",
        "option_A": "Take the unmarked trail to see where it leads.",
        "option_B": "Peer down it and consider a brief detour.",
        "option_C": "Notice it but keep walking.",
        "option_D": "Ignore it and stay on the marked path.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OC4",
        "trait": "Openness",
        "sub_dimension": "Curiosity",
        "scenario": "Encountering a topic that genuinely confuses you feels like:",
        "option_A": "Something exciting — confusion signals there is something real to figure out.",
        "option_B": "Acceptable if the topic eventually becomes clear.",
        "option_C": "Mildly uncomfortable — I prefer working from clarity.",
        "option_D": "A reason to move on to something I already understand.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OC5",
        "trait": "Openness",
        "sub_dimension": "Curiosity",
        "scenario": "You finish your planned reading for the week and have spare time. You are most likely to:",
        "option_A": "Pick up something on a topic I know little about.",
        "option_B": "Choose something adjacent to what I just finished.",
        "option_C": "Re-read something familiar rather than start something new.",
        "option_D": "Switch to a non-reading activity — I've read enough for now.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Openness / Imagination ---
    {
        "id": "OI1",
        "trait": "Openness",
        "sub_dimension": "Imagination",
        "scenario": "When listening to instrumental music, what typically happens in your mind?",
        "option_A": "I build vivid scenes or narratives almost without trying.",
        "option_B": "I occasionally form loose mental images.",
        "option_C": "I notice the melody but don't picture anything specific.",
        "option_D": "Not much — it functions as background sound to me.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OI2",
        "trait": "Openness",
        "sub_dimension": "Imagination",
        "scenario": "Someone asks you to imagine what daily life might look like 300 years from now. You:",
        "option_A": "Construct a detailed mental world with culture, technology, and social norms.",
        "option_B": "Think through several plausible futures before settling on one.",
        "option_C": "Picture a few surface-level changes and move on.",
        "option_D": "Find the exercise too speculative to engage with meaningfully.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OI3",
        "trait": "Openness",
        "sub_dimension": "Imagination",
        "scenario": "While doing a repetitive task like washing dishes, your mind tends to:",
        "option_A": "Spin up elaborate imagined scenarios with little conscious effort.",
        "option_B": "Drift into loose, pleasant daydreams.",
        "option_C": "Run through to-do lists or upcoming plans.",
        "option_D": "Stay focused on finishing the task as quickly as possible.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OI4",
        "trait": "Openness",
        "sub_dimension": "Imagination",
        "scenario": "When I spend time daydreaming, I typically feel it was time well spent.",
        "option_A": "Strongly agree — imagination is where many of my best ideas originate.",
        "option_B": "Somewhat agree — I think it has value even if I can't always justify it.",
        "option_C": "Somewhat disagree — I allow a little but feel I should have been more productive.",
        "option_D": "Strongly disagree — I treat daydreaming as wasted focus time.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "OI5",
        "trait": "Openness",
        "sub_dimension": "Imagination",
        "scenario": "You read a book with an open, ambiguous ending. Your reaction is:",
        "option_A": "Delight — I immediately start imagining multiple possible continuations.",
        "option_B": "Appreciation — I can engage with the intentional ambiguity.",
        "option_C": "Mild dissatisfaction — I generally prefer resolution.",
        "option_D": "Frustration — I wanted a clear conclusion.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Openness / Intellectual_Exploration ---
    {
        "id": "OIE1",
        "trait": "Openness",
        "sub_dimension": "Intellectual_Exploration",
        "scenario": "You encounter a philosophical question with no clear answer. You:",
        "option_A": "Get genuinely absorbed in exploring every angle.",
        "option_B": "Think about it for a while and form a tentative view.",
        "option_C": "Acknowledge it briefly and move on.",
        "option_D": "Dismiss it — questions without answers feel unproductive.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OIE2",
        "trait": "Openness",
        "sub_dimension": "Intellectual_Exploration",
        "scenario": "An expert presents evidence that directly challenges a belief you have held for years. You:",
        "option_A": "Find it genuinely exciting — having a belief successfully challenged is rare and valuable.",
        "option_B": "Acknowledge the challenge and reflect privately afterward.",
        "option_C": "Feel uncomfortable but stay open to eventually revisiting it.",
        "option_D": "Dismiss it — your belief is grounded in your own direct experience.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OIE3",
        "trait": "Openness",
        "sub_dimension": "Intellectual_Exploration",
        "scenario": "Reading non-fiction on a topic completely outside your field feels:",
        "option_A": "One of my favorite pastimes — I seek it out regularly.",
        "option_B": "Enjoyable when the writing is accessible.",
        "option_C": "Acceptable if I can see a practical use for the content.",
        "option_D": "Like an obligation I tend to avoid.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OIE4",
        "trait": "Openness",
        "sub_dimension": "Intellectual_Exploration",
        "scenario": "When I engage with abstract ideas, I find the process itself worthwhile even without a practical outcome.",
        "option_A": "Strongly agree — abstract thinking is often where the most interesting insights live.",
        "option_B": "Somewhat agree — I engage with theory even when the application isn't immediate.",
        "option_C": "Somewhat disagree — I tolerate theory when I can see a use for it.",
        "option_D": "Strongly disagree — I focus on practical knowledge that applies directly to real situations.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "OIE5",
        "trait": "Openness",
        "sub_dimension": "Intellectual_Exploration",
        "scenario": "You notice a concept from one field appearing to explain something in a completely different field. You:",
        "option_A": "Start deliberately mapping the parallel to see how deep it runs.",
        "option_B": "Mention it to someone and explore the connection in conversation.",
        "option_C": "Find it mildly interesting without pursuing it further.",
        "option_D": "Note it as coincidence and move on.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Openness / Preference_for_Novelty ---
    {
        "id": "OPN1",
        "trait": "Openness",
        "sub_dimension": "Preference_for_Novelty",
        "scenario": "At a restaurant you visit often, you see an unfamiliar dish on the menu. You:",
        "option_A": "Order it almost reflexively — eating the same thing twice feels like a missed opportunity.",
        "option_B": "Order it if the description sounds genuinely appealing.",
        "option_C": "Consider it briefly then return to your usual.",
        "option_D": "Order your usual — you know what you like here.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OPN2",
        "trait": "Openness",
        "sub_dimension": "Preference_for_Novelty",
        "scenario": "Your weekend routine starts feeling stale. You:",
        "option_A": "Scrap the routine entirely and try something you've never done on a weekend before.",
        "option_B": "Redesign the weekend with a mix of familiar and new.",
        "option_C": "Swap one small element while keeping everything else the same.",
        "option_D": "Keep the routine — consistency beats novelty.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OPN3",
        "trait": "Openness",
        "sub_dimension": "Preference_for_Novelty",
        "scenario": "When I repeat the same activity the same way for a long time, I start looking for ways to change it.",
        "option_A": "Very true — repetition makes me restless and I actively seek variation.",
        "option_B": "Somewhat true — I look for variety but can tolerate routine for stretches.",
        "option_C": "Somewhat untrue — I like some variety but find routine mostly comfortable.",
        "option_D": "Not true — routine is grounding and I don't feel the urge to change it.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "OPN4",
        "trait": "Openness",
        "sub_dimension": "Preference_for_Novelty",
        "scenario": "A travel app suggests a destination you've never heard of. You:",
        "option_A": "Add it to your list immediately — the unfamiliarity is part of the appeal.",
        "option_B": "Look it up to see if it's worth considering.",
        "option_C": "Glance briefly then return to your researched shortlist.",
        "option_D": "Ignore it and stick to places you've already vetted.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OPN5",
        "trait": "Openness",
        "sub_dimension": "Preference_for_Novelty",
        "scenario": "An app you use daily gets a major interface overhaul. You:",
        "option_A": "Enjoy the disruption — a changed layout might reveal a better workflow.",
        "option_B": "Explore the new layout with neutral curiosity.",
        "option_C": "Adapt reluctantly, trying to recreate your old habits.",
        "option_D": "Feel frustrated — you want the familiar version back.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Openness / Creativity ---
    {
        "id": "OCR1",
        "trait": "Openness",
        "sub_dimension": "Creativity",
        "scenario": "You have an hour of free time with no plans. You are most likely to:",
        "option_A": "Dive into a creative project — writing, building, or designing something.",
        "option_B": "Dabble in a small creative activity like doodling or sketching an idea.",
        "option_C": "Rest or do something low-effort.",
        "option_D": "Scroll something familiar or watch content without much thought.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OCR2",
        "trait": "Openness",
        "sub_dimension": "Creativity",
        "scenario": "You are stuck mid-project and your original approach isn't working. You:",
        "option_A": "Deliberately choose the most unconventional angle you can think of to force a new perspective.",
        "option_B": "Try a different approach even if it feels unfamiliar.",
        "option_C": "Take a break and return hoping the path becomes clearer.",
        "option_D": "Keep applying the same method with more effort.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OCR3",
        "trait": "Openness",
        "sub_dimension": "Creativity",
        "scenario": "When I encounter a problem with no obvious solution, I tend to generate many possible approaches before settling on one.",
        "option_A": "Very true — generating varied options feels natural to me.",
        "option_B": "Somewhat true — I try a few angles before converging.",
        "option_C": "Somewhat untrue — I usually try one or two methods before committing.",
        "option_D": "Not true — I identify the most logical approach and apply it directly.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "OCR4",
        "trait": "Openness",
        "sub_dimension": "Creativity",
        "scenario": "While cooking dinner you realize you're missing a key ingredient. You:",
        "option_A": "Treat it as a challenge and improvise an entirely different version of the dish.",
        "option_B": "Think through flavors and attempt a reasonable substitute.",
        "option_C": "Find the simplest swap available and proceed cautiously.",
        "option_D": "Order takeout — you don't want to risk ruining the dish.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "OCR5",
        "trait": "Openness",
        "sub_dimension": "Creativity",
        "scenario": "Someone gives you a blank notebook as a gift. You:",
        "option_A": "Immediately start filling it with ideas, sketches, and experiments.",
        "option_B": "Gradually turn it into a personal journal or sketchbook.",
        "option_C": "Use it for practical notes and to-do lists.",
        "option_D": "Leave it on a shelf — you're not sure what to use it for.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # =========================================================
    # CONSCIENTIOUSNESS — 5 sub-dimensions × 5 questions = 25
    # =========================================================

    # --- Conscientiousness / Planning ---
    {
        "id": "CP1",
        "trait": "Conscientiousness",
        "sub_dimension": "Planning",
        "scenario": "You have an important assignment due in two weeks. When do you actually start?",
        "option_A": "I map out the work on day one and set personal internal deadlines for each section.",
        "option_B": "Within the first few days — I like having time to revise.",
        "option_C": "About a week in, when it starts feeling urgent.",
        "option_D": "The day before — pressure is when I focus best.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CP2",
        "trait": "Conscientiousness",
        "sub_dimension": "Planning",
        "scenario": "You have three tasks due on the same day. How do you handle the week before?",
        "option_A": "I assign each task a specific day and protect that time so nothing overlaps.",
        "option_B": "I spread them loosely across the week and adjust as needed.",
        "option_C": "I remind myself a few days before and push through in a rush.",
        "option_D": "I don't think much about it until the day itself arrives.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CP3",
        "trait": "Conscientiousness",
        "sub_dimension": "Planning",
        "scenario": "Making detailed plans before starting a project feels:",
        "option_A": "Essential — a clear plan consistently saves time and reduces errors.",
        "option_B": "Helpful for larger projects where coordination matters.",
        "option_C": "Useful in theory but not always how I actually work.",
        "option_D": "Like over-engineering — I prefer to dive in and adapt.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CP4",
        "trait": "Conscientiousness",
        "sub_dimension": "Planning",
        "scenario": "A spontaneous opportunity conflicts with a plan you set for yourself. You:",
        "option_A": "Stick to the plan — I made this time for a reason.",
        "option_B": "Suggest a compromise that lets you do both partially.",
        "option_C": "Go with the spontaneous option and tell yourself you'll catch up later.",
        "option_D": "Drop the plan without much deliberation — spontaneous options are usually more interesting.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CP5",
        "trait": "Conscientiousness",
        "sub_dimension": "Planning",
        "scenario": "When I have upcoming deadlines, I typically have a clear plan well before the due date arrives.",
        "option_A": "Almost always — I build buffer time into everything I plan.",
        "option_B": "Usually — I plan ahead effectively most of the time.",
        "option_C": "Sometimes — I plan but still find myself rushing more than I'd like.",
        "option_D": "Rarely — I tend to rely on last-minute pressure to get things done.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Conscientiousness / Discipline ---
    {
        "id": "CD1",
        "trait": "Conscientiousness",
        "sub_dimension": "Discipline",
        "scenario": "You are working on something important when a more enjoyable distraction appears. You:",
        "option_A": "Stay on the task until it's done — I don't negotiate with distractions mid-flow.",
        "option_B": "Finish the section I'm on, then allow the distraction as a reward.",
        "option_C": "Tell myself just a quick break but end up spending much longer on the distraction.",
        "option_D": "Switch to the enjoyable thing — I'll come back to the task later.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CD2",
        "trait": "Conscientiousness",
        "sub_dimension": "Discipline",
        "scenario": "You committed to waking up at 6am daily. On day five you sleep poorly. You:",
        "option_A": "Get up at 6am regardless — one bad night doesn't override my commitment.",
        "option_B": "Get up after one snooze, feeling rough but functional.",
        "option_C": "Snooze twice and get up significantly late, telling yourself recovery matters.",
        "option_D": "Turn off the alarm and sleep in — rest wins today.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CD3",
        "trait": "Conscientiousness",
        "sub_dimension": "Discipline",
        "scenario": "When my motivation for a habit drops, I typically:",
        "option_A": "Continue the habit regardless — I treat commitments as fixed regardless of how I feel.",
        "option_B": "Push through low-motivation periods even when it's uncomfortable.",
        "option_C": "Struggle through dips but eventually quit more often than I'd like.",
        "option_D": "Stop the habit — I need ongoing motivation to sustain behaviors.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "CD4",
        "trait": "Conscientiousness",
        "sub_dimension": "Discipline",
        "scenario": "You are working from home with no supervision. Your actual output compared to your planned output is:",
        "option_A": "The same as always — my discipline doesn't depend on whether anyone is watching.",
        "option_B": "Mostly on track with a few dips in focus.",
        "option_C": "Decent but fragmented — I catch up toward the end of the day.",
        "option_D": "About half — the environment makes it easy to drift.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CD5",
        "trait": "Conscientiousness",
        "sub_dimension": "Discipline",
        "scenario": "You're building a skill that requires daily practice. Some days feel unproductive. You:",
        "option_A": "Show up especially on flat days — I understand that invisible progress is still progress.",
        "option_B": "Push through even on flat days, though I feel uncertain about the payoff.",
        "option_C": "Practice only when I feel sufficiently motivated.",
        "option_D": "Skip flat days — if it's not clicking, practice feels pointless.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Conscientiousness / Responsibility ---
    {
        "id": "CR1",
        "trait": "Conscientiousness",
        "sub_dimension": "Responsibility",
        "scenario": "You make an error in a report your team submitted. Nobody noticed yet. You:",
        "option_A": "Disclose it immediately to the right people and help fix the impact.",
        "option_B": "Mention it quietly to one person without making it formal.",
        "option_C": "Wait to see if it causes a problem before deciding whether to flag it.",
        "option_D": "Leave it — if no one noticed, the impact is probably minimal.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CR2",
        "trait": "Conscientiousness",
        "sub_dimension": "Responsibility",
        "scenario": "You promised to review a colleague's document but forgot until the night before their deadline. You:",
        "option_A": "Call them immediately, apologize fully, and do a proper review however late it runs.",
        "option_B": "Apologize and offer to review it now, even though time is short.",
        "option_C": "Send a quick skim and tell them it was the best you could do.",
        "option_D": "Hope they found someone else and say nothing.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CR3",
        "trait": "Conscientiousness",
        "sub_dimension": "Responsibility",
        "scenario": "When I take on a commitment, I follow through completely.",
        "option_A": "Almost always — my word is something I take seriously.",
        "option_B": "Usually — I occasionally fall short but try to make it right.",
        "option_C": "Sometimes — I follow through on things that feel most important.",
        "option_D": "Rarely — I often struggle to deliver fully on what I've promised.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CR4",
        "trait": "Conscientiousness",
        "sub_dimension": "Responsibility",
        "scenario": "A group project goes badly and your contribution was weaker than expected. You:",
        "option_A": "Own it clearly — explain what went wrong on your end and what you'd do differently.",
        "option_B": "Admit to the group that your section fell short.",
        "option_C": "Acknowledge it vaguely if directly asked but avoid specifics.",
        "option_D": "Say nothing and hope others don't focus on your part.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CR5",
        "trait": "Conscientiousness",
        "sub_dimension": "Responsibility",
        "scenario": "When something more appealing comes up after I've made a commitment, I:",
        "option_A": "Honor the commitment — it's non-negotiable for me.",
        "option_B": "Feel tempted but usually follow through on what I promised.",
        "option_C": "Occasionally shift priorities when the alternative seems worth it.",
        "option_D": "Frequently prioritize what feels better in the moment.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Conscientiousness / Goal_Orientation ---
    {
        "id": "CGO1",
        "trait": "Conscientiousness",
        "sub_dimension": "Goal_Orientation",
        "scenario": "You have a vague wish to improve your fitness but no structure around it. Over the next month:",
        "option_A": "I define a specific target, set a timeline, and track progress weekly.",
        "option_B": "I set a loose goal and make some progress, even if inconsistent.",
        "option_C": "I make a few attempts but they fade without a clear plan.",
        "option_D": "It stays a wish — nothing changes.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CGO2",
        "trait": "Conscientiousness",
        "sub_dimension": "Goal_Orientation",
        "scenario": "Six weeks into working toward a goal, progress feels slower than expected. You:",
        "option_A": "Assess what's slowing progress, adjust the method, and keep the goal intact.",
        "option_B": "Push through but feel uncertain about whether the approach is working.",
        "option_C": "Lose motivation and let the effort gradually taper.",
        "option_D": "Take the slow progress as a sign the goal wasn't realistic and scale it back.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CGO3",
        "trait": "Conscientiousness",
        "sub_dimension": "Goal_Orientation",
        "scenario": "I tend to set specific, measurable goals rather than vague intentions.",
        "option_A": "Almost always — vague intentions rarely produce real results.",
        "option_B": "Often — I find structure helpful for most goals.",
        "option_C": "Sometimes — I set loose goals but rarely get specific.",
        "option_D": "Rarely — I prefer to keep things open and flexible.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CGO4",
        "trait": "Conscientiousness",
        "sub_dimension": "Goal_Orientation",
        "scenario": "When I start new goals with enthusiasm, I typically:",
        "option_A": "See them through — finishing what I start is a core part of how I operate.",
        "option_B": "Complete most of them even when momentum dips.",
        "option_C": "Complete some but abandon others when interest fades.",
        "option_D": "Abandon most before completion — I have many unfinished goals.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "CGO5",
        "trait": "Conscientiousness",
        "sub_dimension": "Goal_Orientation",
        "scenario": "At the end of a year you review your goals and find you completed three of five. You:",
        "option_A": "Conduct a deliberate review — categorize each goal as completed, abandoned, or blocked and use it to set smarter ones.",
        "option_B": "Reflect on which goals fell short and why before setting new ones.",
        "option_C": "Accept it without much analysis and set a similar list next year.",
        "option_D": "Feel the year was a failure and lose motivation to set goals the following year.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Conscientiousness / Time_Management ---
    {
        "id": "CTM1",
        "trait": "Conscientiousness",
        "sub_dimension": "Time_Management",
        "scenario": "You have five tasks today and no set schedule. How does the day actually unfold?",
        "option_A": "I assign each task a time block at the start of the day and work through them in sequence.",
        "option_B": "I roughly prioritize and get through most of them even if the order shifts.",
        "option_C": "I start one thing then jump around and end the day with several half-done.",
        "option_D": "I drift between tasks based on mood and finish fewer than planned.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CTM2",
        "trait": "Conscientiousness",
        "sub_dimension": "Time_Management",
        "scenario": "You consistently underestimate how long tasks take. You:",
        "option_A": "Track how long tasks actually take and use that data to calibrate future estimates.",
        "option_B": "Add rough buffer time when planning, even if I'm not precise about it.",
        "option_C": "Try to go faster to compensate but the problem keeps recurring.",
        "option_D": "Accept it as part of how I work — I've always been this way.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CTM3",
        "trait": "Conscientiousness",
        "sub_dimension": "Time_Management",
        "scenario": "At the end of a busy day, I can clearly identify what I actually accomplished.",
        "option_A": "Almost always — I regularly check whether what I'm spending time on matches what matters.",
        "option_B": "Usually — I try to prioritize high-impact work throughout the day.",
        "option_C": "Sometimes — I get pulled into lower-value tasks more than I'd like.",
        "option_D": "Rarely — busyness and productivity feel the same to me in the moment.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "CTM4",
        "trait": "Conscientiousness",
        "sub_dimension": "Time_Management",
        "scenario": "A personally important task keeps getting displaced by reactive work. Over weeks it never gets done. You:",
        "option_A": "Schedule it as a fixed, non-negotiable block — if it has no protected time, it always loses to urgent.",
        "option_B": "Try harder to find pockets of time when the reactive load lightens.",
        "option_C": "Keep it on the list and feel guilty that it hasn't moved.",
        "option_D": "Accept that reactive work is just the nature of the role.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "CTM5",
        "trait": "Conscientiousness",
        "sub_dimension": "Time_Management",
        "scenario": "Someone requests a meeting during your most productive hours. You:",
        "option_A": "Protect that block and offer two alternative slots — peak hours are non-negotiable where possible.",
        "option_B": "Politely ask if there's flexibility and suggest an alternative time.",
        "option_C": "Accept but feel frustrated about losing that window.",
        "option_D": "Accept without question — I don't think about protecting certain hours.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # =========================================================
    # EXTRAVERSION — 5 sub-dimensions × 5 questions = 25
    # =========================================================

    # --- Extraversion / Social_Energy ---
    {
        "id": "ESE1",
        "trait": "Extraversion",
        "sub_dimension": "Social_Energy",
        "scenario": "You have had back-to-back social plans all weekend. Sunday evening you feel:",
        "option_A": "Genuinely energized — you'd have said yes to Sunday evening plans too.",
        "option_B": "Satisfied — a full social weekend leaves you feeling good.",
        "option_C": "A little tired but glad you went.",
        "option_D": "Drained and relieved it's over — you need the week to recover.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ESE2",
        "trait": "Extraversion",
        "sub_dimension": "Social_Energy",
        "scenario": "You have a Saturday with no plans or social obligations. By mid-afternoon you feel:",
        "option_A": "Restless — you've already reached out hoping something comes together.",
        "option_B": "A bit flat — you function better with at least one social touchpoint.",
        "option_C": "Fine at first, but ready for some low-key contact by now.",
        "option_D": "Relieved and content — this is exactly what you needed.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "ESE3",
        "trait": "Extraversion",
        "sub_dimension": "Social_Energy",
        "scenario": "You finish a draining workday and a friend texts asking to grab dinner. Your honest instinct is:",
        "option_A": "To go immediately — people are exactly what you need after a hard day.",
        "option_B": "To go — being around someone you like usually helps you reset.",
        "option_C": "To stay in, but you might go if they really want company.",
        "option_D": "To be alone — more social interaction sounds exhausting right now.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ESE4",
        "trait": "Extraversion",
        "sub_dimension": "Social_Energy",
        "scenario": "You are given the choice to work on a project solo or with a team. Everything else is equal. You choose:",
        "option_A": "The team without question — working alongside people gives me energy solo work doesn't.",
        "option_B": "The team — collaboration tends to make the work better.",
        "option_C": "Probably solo, but I'd consider the team if the people were right.",
        "option_D": "Solo without hesitation — I do my best thinking alone.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ESE5",
        "trait": "Extraversion",
        "sub_dimension": "Social_Energy",
        "scenario": "After a full day with people, compared to a full day alone, you feel:",
        "option_A": "More charged — real human contact lifts my baseline.",
        "option_B": "Roughly even — I adapt to both without much cost.",
        "option_C": "About the same but needing quiet afterward to feel like myself.",
        "option_D": "More depleted — regardless of how much I liked the people.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Extraversion / Assertiveness ---
    {
        "id": "EAS1",
        "trait": "Extraversion",
        "sub_dimension": "Assertiveness",
        "scenario": "You are in a group discussion and have a strong opinion that contradicts what most people are saying. You:",
        "option_A": "State your position directly and make the case for it without waiting for consensus.",
        "option_B": "Share your view clearly even if it creates some tension.",
        "option_C": "Wait to see if anyone else raises a similar point before speaking.",
        "option_D": "Stay quiet — going against the group rarely ends well.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "EAS2",
        "trait": "Extraversion",
        "sub_dimension": "Assertiveness",
        "scenario": "Your restaurant order arrives clearly wrong. You:",
        "option_A": "Call the server over immediately, state what's wrong, and ensure it's corrected.",
        "option_B": "Politely flag it to the server and ask for the correct order.",
        "option_C": "Eat most of it and mention it briefly when the bill comes.",
        "option_D": "Eat it anyway — sending food back feels uncomfortable.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "EAS3",
        "trait": "Extraversion",
        "sub_dimension": "Assertiveness",
        "scenario": "When someone asks me to take on more than I can handle, I typically:",
        "option_A": "Decline clearly and without excessive apology when capacity is the issue.",
        "option_B": "Decline when I genuinely lack capacity, even if it feels uncomfortable.",
        "option_C": "Hesitate to decline even when I know I should.",
        "option_D": "Say yes and feel resentful about it afterward.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "EAS4",
        "trait": "Extraversion",
        "sub_dimension": "Assertiveness",
        "scenario": "A salary negotiation opens with an offer below your expectation. You:",
        "option_A": "Counter with a specific figure backed by reasoning and hold the position until resolved.",
        "option_B": "Ask if there's flexibility without naming a specific number.",
        "option_C": "Express mild disappointment but don't make a formal counteroffer.",
        "option_D": "Accept it — negotiating feels presumptuous and you don't want to risk the offer.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "EAS5",
        "trait": "Extraversion",
        "sub_dimension": "Assertiveness",
        "scenario": "Someone takes credit for an idea you shared in a meeting last week. You:",
        "option_A": "Correct the record in the room — calmly and factually note the idea came from you.",
        "option_B": "Bring it up with the person privately and clarify the idea was yours.",
        "option_C": "Mention it quietly to a colleague but not directly to the person.",
        "option_D": "Say nothing — proving ownership after the fact feels awkward.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Extraversion / Expressiveness ---
    {
        "id": "EEX1",
        "trait": "Extraversion",
        "sub_dimension": "Expressiveness",
        "scenario": "You receive genuinely good news in a group setting. You:",
        "option_A": "React fully and immediately — you might jump up, laugh loudly, or pull someone into a hug.",
        "option_B": "React visibly — people around you can clearly tell you're pleased.",
        "option_C": "Smile and say something brief but keep the reaction contained.",
        "option_D": "Feel it internally but show very little on the outside.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "EEX2",
        "trait": "Extraversion",
        "sub_dimension": "Expressiveness",
        "scenario": "Someone asks how your week has been. You:",
        "option_A": "Give a full account — highs, lows, what frustrated you, what excited you — you enjoy talking it through.",
        "option_B": "Give a real answer that includes how certain things affected you.",
        "option_C": "Share the basic shape of the week without getting into how you felt.",
        "option_D": "Give a short factual answer — 'fine' or 'busy' — and leave it there.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "EEX3",
        "trait": "Extraversion",
        "sub_dimension": "Expressiveness",
        "scenario": "People who know me well would say my feelings are usually visible, even when I haven't said anything.",
        "option_A": "Very true — I don't separate what I feel from what I show and wouldn't want to.",
        "option_B": "Somewhat true — my feelings surface even when I don't intend them to.",
        "option_C": "Somewhat untrue — close people can read me, but most cannot.",
        "option_D": "Not true — I process internally and show a composed version to others.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "EEX4",
        "trait": "Extraversion",
        "sub_dimension": "Expressiveness",
        "scenario": "You are telling a story to a group. You naturally:",
        "option_A": "Use your whole body — voice shifts, gestures, facial expressions — feeding off the group's reactions.",
        "option_B": "Use tone and pacing to bring it to life — you want people to feel what it was like.",
        "option_C": "Include the key details but don't perform it.",
        "option_D": "Relay the facts plainly and keep it short.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "EEX5",
        "trait": "Extraversion",
        "sub_dimension": "Expressiveness",
        "scenario": "You are excited about an upcoming trip or event. That excitement in daily interactions:",
        "option_A": "Spills into everything — you bring it up constantly and want others to feel what you're feeling.",
        "option_B": "Surfaces naturally when it comes up and your enthusiasm comes through.",
        "option_C": "Comes up once with a close person but you don't mention it again.",
        "option_D": "Stays mostly internal — you don't share it much before it happens.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Extraversion / Social_Risk_Taking ---
    {
        "id": "ESRT1",
        "trait": "Extraversion",
        "sub_dimension": "Social_Risk_Taking",
        "scenario": "You spot someone across a room whose work you deeply admire. You've never met. You:",
        "option_A": "Walk over, introduce yourself, and tell them directly what their work means to you.",
        "option_B": "Look for a natural moment to cross paths and use it if it comes.",
        "option_C": "Wait to see if a mutual connection introduces you.",
        "option_D": "Stay where you are — approaching someone uninvited feels presumptuous.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ESRT2",
        "trait": "Extraversion",
        "sub_dimension": "Social_Risk_Taking",
        "scenario": "A karaoke machine appears at a social event. You haven't sung publicly before. You:",
        "option_A": "Go up alone and pick a song you actually want to sing — the discomfort is part of the fun.",
        "option_B": "Go up if someone comes with you — shared awkwardness makes it easier.",
        "option_C": "Watch and enjoy others but don't consider going up.",
        "option_D": "Make it clear you're not participating — public singing is a firm boundary.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ESRT3",
        "trait": "Extraversion",
        "sub_dimension": "Social_Risk_Taking",
        "scenario": "In group settings, I typically speak up even when I'm unsure how what I say will land.",
        "option_A": "Almost always — I'd rather try something that falls flat than stay quiet.",
        "option_B": "Usually — I speak up even if the outcome is uncertain.",
        "option_C": "Sometimes — I hesitate more than I'd ideally like.",
        "option_D": "Rarely — I often self-censor because of concern about how I'll come across.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "ESRT4",
        "trait": "Extraversion",
        "sub_dimension": "Social_Risk_Taking",
        "scenario": "You pitch an idea in a group and it gets a lukewarm response. Afterward you:",
        "option_A": "Take it in stride and pitch the next idea without hesitation — one flat response doesn't recalibrate you.",
        "option_B": "Absorb the reaction and try again when you feel more confident.",
        "option_C": "Pull back for the rest of the session.",
        "option_D": "Feel embarrassed and become reluctant to offer ideas in that group again.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ESRT5",
        "trait": "Extraversion",
        "sub_dimension": "Social_Risk_Taking",
        "scenario": "You start a new job and your team goes out for drinks your first week. You know nobody. You:",
        "option_A": "Treat it like any social situation — introduce yourself freely, share stories, and leave having made real contact.",
        "option_B": "Introduce yourself to people you haven't spoken to yet and join forming conversations.",
        "option_C": "Engage in one-on-one conversations when they happen but don't initiate much.",
        "option_D": "Go but stay quiet and observe — it's too early to take up space.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Extraversion / Leadership_Initiative ---
    {
        "id": "ELI1",
        "trait": "Extraversion",
        "sub_dimension": "Leadership_Initiative",
        "scenario": "Your team has no clear direction on a project and nobody is stepping up to lead. You:",
        "option_A": "Step in naturally — map out the approach, assign roles, and get the group moving.",
        "option_B": "Suggest a rough structure to the group and help move things forward informally.",
        "option_C": "Contribute when asked but avoid owning the coordination.",
        "option_D": "Wait for someone with more authority to take charge.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ELI2",
        "trait": "Extraversion",
        "sub_dimension": "Leadership_Initiative",
        "scenario": "A meeting ends without clear next steps and people start drifting out. You:",
        "option_A": "Before anyone leaves, call it out — summarize decisions, name owners, and confirm timelines.",
        "option_B": "Send a summary email afterward with what you understood the next steps to be.",
        "option_C": "Feel frustrated but assume the organizer will follow up.",
        "option_D": "Leave with everyone — it wasn't your meeting to close.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ELI3",
        "trait": "Extraversion",
        "sub_dimension": "Leadership_Initiative",
        "scenario": "In ambiguous group situations, I tend to step up and take charge rather than wait for someone else to.",
        "option_A": "Strongly agree — I tend to naturally step forward when direction is unclear.",
        "option_B": "Somewhat agree — I step up when no one else does.",
        "option_C": "Somewhat disagree — I lead when asked but don't seek it out.",
        "option_D": "Strongly disagree — I'm more comfortable as a contributor than a driver.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "ELI4",
        "trait": "Extraversion",
        "sub_dimension": "Leadership_Initiative",
        "scenario": "You notice a recurring problem at work that nobody is officially responsible for fixing. You:",
        "option_A": "Take ownership — draft a proposal, find the right people, and drive it through without being asked.",
        "option_B": "Raise it with the relevant person and suggest a possible fix.",
        "option_C": "Mention it to a colleague but don't take it further.",
        "option_D": "Note it privately and assume someone above you will eventually address it.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ELI5",
        "trait": "Extraversion",
        "sub_dimension": "Leadership_Initiative",
        "scenario": "You have an idea for a community initiative that doesn't exist yet. Launching it means public ownership and organizing others. You:",
        "option_A": "Launch it — you put your name to it, recruit who you need, and treat the organizational work as part of the project.",
        "option_B": "Start small — test it with a few people and build gradually.",
        "option_C": "Share the idea with someone else hoping they'll take it forward.",
        "option_D": "The idea stays an idea — the visibility and coordination required are too much.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # =========================================================
    # AGREEABLENESS — 5 sub-dimensions × 5 questions = 25
    # =========================================================

    # --- Agreeableness / Empathy ---
    {
        "id": "AEM1",
        "trait": "Agreeableness",
        "sub_dimension": "Empathy",
        "scenario": "A colleague is visibly upset about something personal. You have a deadline in an hour. You:",
        "option_A": "Give them a few minutes now and offer to talk properly after your deadline.",
        "option_B": "Acknowledge it genuinely and check in after your deadline.",
        "option_C": "Acknowledge it briefly and return to your task.",
        "option_D": "Focus on your work — their situation isn't your responsibility right now.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AEM2",
        "trait": "Agreeableness",
        "sub_dimension": "Empathy",
        "scenario": "A friend describes a setback that feels minor to you but clearly matters deeply to them. You:",
        "option_A": "Listen fully and reflect back what they seem to be feeling without minimizing it.",
        "option_B": "Listen and ask what kind of support they're looking for.",
        "option_C": "Acknowledge it and offer your perspective on why it might not be as bad as it seems.",
        "option_D": "Point out the practical solution — getting to the answer is most helpful.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AEM3",
        "trait": "Agreeableness",
        "sub_dimension": "Empathy",
        "scenario": "When someone is visibly upset about something, I usually understand what they are feeling even without them saying it.",
        "option_A": "Almost always — I pick up on emotional signals readily and accurately.",
        "option_B": "Usually — I can generally connect to what someone is experiencing.",
        "option_C": "Sometimes — I get it intellectually but don't always feel it.",
        "option_D": "Rarely — I find strong emotional reactions difficult to interpret or relate to.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "AEM4",
        "trait": "Agreeableness",
        "sub_dimension": "Empathy",
        "scenario": "You are listening to someone describe a problem and you can already see the solution. You:",
        "option_A": "Listen fully, then share what you see — the solution is only useful once they feel heard.",
        "option_B": "Ask whether they want advice or just want to be heard before saying anything.",
        "option_C": "Offer the solution as soon as there's a natural pause.",
        "option_D": "Share the solution immediately — getting to the answer is the most helpful thing you can do.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AEM5",
        "trait": "Agreeableness",
        "sub_dimension": "Empathy",
        "scenario": "Someone in your group is clearly being left out of a conversation. Nobody else has noticed. You:",
        "option_A": "Directly invite them in — you ask what they think so they're visibly included.",
        "option_B": "Find a natural way to bring the person in without making the exclusion obvious.",
        "option_C": "Mention it quietly to someone else in the group.",
        "option_D": "Notice it but don't intervene — drawing attention might make things worse.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Agreeableness / Cooperation ---
    {
        "id": "ACO1",
        "trait": "Agreeableness",
        "sub_dimension": "Cooperation",
        "scenario": "Your team votes on an approach you think is suboptimal. You've raised your concern and been outvoted. You:",
        "option_A": "Accept the decision and execute it fully — the team chose and that commitment matters.",
        "option_B": "Execute it but put on record that you flagged the issue.",
        "option_C": "Comply externally while quietly doing parts of it your own way.",
        "option_D": "Keep raising the issue — if you think the approach is wrong you owe it to the project.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ACO2",
        "trait": "Agreeableness",
        "sub_dimension": "Cooperation",
        "scenario": "A group compromise satisfies everyone moderately but doesn't reflect anyone's best idea, including yours. You feel:",
        "option_A": "Satisfied — a decision everyone owns tends to get implemented better than one strong vision that others resist.",
        "option_B": "Neutral — I can live with compromise as long as the process was fair.",
        "option_C": "Reluctant — I accept it but look for ways to incorporate more of my original idea.",
        "option_D": "Frustrated — a watered-down compromise produces worse outcomes than one strong vision.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ACO3",
        "trait": "Agreeableness",
        "sub_dimension": "Cooperation",
        "scenario": "When collaborating with someone whose working style differs significantly from mine, I:",
        "option_A": "Adapt readily — I consider style adjustment a basic requirement of good collaboration.",
        "option_B": "Adapt reasonably well when it serves the shared goal.",
        "option_C": "Try to adapt but it costs me focus and energy.",
        "option_D": "Work much better when others match my style.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "ACO4",
        "trait": "Agreeableness",
        "sub_dimension": "Cooperation",
        "scenario": "Your team wants to celebrate a project completion as a group. You'd rather move to the next task. You:",
        "option_A": "Participate fully — shared rituals matter to team cohesion even when I don't personally feel the need.",
        "option_B": "Suggest a shorter version that still acknowledges the work.",
        "option_C": "Attend briefly and leave as soon as reasonably possible.",
        "option_D": "Skip it — I'm transparent about valuing momentum over team rituals.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ACO5",
        "trait": "Agreeableness",
        "sub_dimension": "Cooperation",
        "scenario": "You discover mid-project that a colleague interpreted the brief very differently. Both interpretations are defensible. You:",
        "option_A": "Explore both interpretations together and decide which to align on before proceeding.",
        "option_B": "Present both to a third party for a tie-breaking perspective.",
        "option_C": "Make the case for your interpretation — you believe it's stronger.",
        "option_D": "Split the work along each interpretation and see which produces better results.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Agreeableness / Trust ---
    {
        "id": "ATR1",
        "trait": "Agreeableness",
        "sub_dimension": "Trust",
        "scenario": "You meet someone who is immediately warm and open with you. You:",
        "option_A": "Open up genuinely in return — if someone leads with trust you meet them there.",
        "option_B": "Reciprocate naturally — warmth offered in good faith deserves warmth back.",
        "option_C": "Enjoy the warmth but don't match it — you wait to see if it holds over time.",
        "option_D": "Stay measured — people who open up quickly often have an ulterior motive.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ATR2",
        "trait": "Agreeableness",
        "sub_dimension": "Trust",
        "scenario": "You delegate an important task to a colleague who asks for minimal check-ins. You:",
        "option_A": "Hand it over completely — if I've delegated, I don't second-guess the person I chose.",
        "option_B": "Give them the space they asked for and trust the output will come.",
        "option_C": "Agree to minimal check-ins but set one mid-point touchpoint as a condition.",
        "option_D": "Agree verbally but find indirect ways to monitor progress anyway.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ATR3",
        "trait": "Agreeableness",
        "sub_dimension": "Trust",
        "scenario": "I generally assume people have good intentions unless they give me a clear reason to think otherwise.",
        "option_A": "Almost always — assuming bad intent has a social cost I'm not willing to pay by default.",
        "option_B": "Usually — I start from trust and revise only if evidence warrants it.",
        "option_C": "Sometimes — I extend initial good faith but stay alert.",
        "option_D": "Rarely — I prefer to verify before I extend trust.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ATR4",
        "trait": "Agreeableness",
        "sub_dimension": "Trust",
        "scenario": "A friend cancels plans last minute for the second time this month. They give a plausible reason. You:",
        "option_A": "Accept it without tracking it — keeping score of cancellations isn't how you operate in friendships.",
        "option_B": "Give them the benefit of the doubt — people have complicated lives.",
        "option_C": "Take the reason at face value this time but you're paying attention now.",
        "option_D": "Two cancellations is a pattern — you're skeptical of the reason regardless.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ATR5",
        "trait": "Agreeableness",
        "sub_dimension": "Trust",
        "scenario": "With people I haven't known for long, I extend reasonable trust fairly early.",
        "option_A": "Very true — I extend trust readily and don't require time as the main basis.",
        "option_B": "Mostly true — I extend reasonable trust early and revise based on experience.",
        "option_C": "Somewhat untrue — I'm cautious with newer relationships.",
        "option_D": "Not true — trust is something I extend only after significant time.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Agreeableness / Conflict_Handling ---
    {
        "id": "ACH1",
        "trait": "Agreeableness",
        "sub_dimension": "Conflict_Handling",
        "scenario": "You and a close friend have an unresolved argument from last week. Neither has brought it up. You:",
        "option_A": "Address it directly and soon — you'd rather have an uncomfortable conversation than carry the tension.",
        "option_B": "Bring it up when the moment feels right — unresolved things tend to compound.",
        "option_C": "Wait for them to bring it up first.",
        "option_D": "Leave it — if it hasn't surfaced again, maybe it's resolved itself.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ACH2",
        "trait": "Agreeableness",
        "sub_dimension": "Conflict_Handling",
        "scenario": "When I know a difficult conversation is necessary, I typically:",
        "option_A": "Have it without much delay — necessary conversations are part of maintaining good relationships.",
        "option_B": "Push through my discomfort and have it, even if I wait longer than ideal.",
        "option_C": "Delay it longer than I should but eventually follow through.",
        "option_D": "Avoid it for as long as possible — the discomfort of conflict is a strong deterrent.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "ACH3",
        "trait": "Agreeableness",
        "sub_dimension": "Conflict_Handling",
        "scenario": "You give honest feedback and the other person responds with anger. You:",
        "option_A": "Acknowledge their reaction without withdrawing the feedback — both things can be true at once.",
        "option_B": "Stay calm and wait for the emotional temperature to drop before continuing.",
        "option_C": "Disengage temporarily and revisit when the anger passes.",
        "option_D": "Apologize and soften the feedback — their reaction signals you went too far.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ACH4",
        "trait": "Agreeableness",
        "sub_dimension": "Conflict_Handling",
        "scenario": "You realize mid-conflict that you're partly wrong, but fully conceding would feel like losing. You:",
        "option_A": "Acknowledge the part you got wrong while continuing to hold the part you still believe.",
        "option_B": "Acknowledge the full extent you're wrong even if it shifts the dynamic against you.",
        "option_C": "Pause the conversation — you need to think before you can engage honestly.",
        "option_D": "Hold your full position — you'll revisit your thinking privately after the conversation.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "ACH5",
        "trait": "Agreeableness",
        "sub_dimension": "Conflict_Handling",
        "scenario": "A conflict with someone keeps recurring around the same issue. It's been addressed before but nothing changes. You:",
        "option_A": "Find a structural change that removes the recurring trigger rather than having the same conversation again.",
        "option_B": "Raise the pattern itself directly — the recurrence is now the problem.",
        "option_C": "Reassess whether the relationship is sustainable given the ongoing friction.",
        "option_D": "Accept it as a permanent feature of the relationship and stop expecting change.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },

    # --- Agreeableness / Helping_Behavior ---
    {
        "id": "AHB1",
        "trait": "Agreeableness",
        "sub_dimension": "Helping_Behavior",
        "scenario": "A colleague asks for help with something that would take an hour you don't have today. You:",
        "option_A": "Help with the most critical part now and schedule time to complete the rest tomorrow.",
        "option_B": "Tell them you can't today but offer a specific time tomorrow.",
        "option_C": "Suggest they ask someone with more availability today.",
        "option_D": "Decline — your own work has to come first today.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AHB2",
        "trait": "Agreeableness",
        "sub_dimension": "Helping_Behavior",
        "scenario": "You notice a stranger struggling with something in public. Nobody else is helping. You:",
        "option_A": "Step in directly — waiting to be asked when the need is obvious wastes everyone's time.",
        "option_B": "Ask briefly if they'd like a hand.",
        "option_C": "Slow down and make eye contact in case they want to signal they need help.",
        "option_D": "Walk past — unsolicited help can feel intrusive.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AHB3",
        "trait": "Agreeableness",
        "sub_dimension": "Helping_Behavior",
        "scenario": "I regularly go out of my way to help others even when it costs me time or energy.",
        "option_A": "Almost always — others' needs feel as immediate to me as my own.",
        "option_B": "Often — I regularly prioritize helping others even when it's inconvenient.",
        "option_C": "Sometimes — I help when the need is clear and the cost is manageable.",
        "option_D": "Rarely — I help when it's convenient but don't stretch for it.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AHB4",
        "trait": "Agreeableness",
        "sub_dimension": "Helping_Behavior",
        "scenario": "You are running low on your own resources — time, energy — and someone asks for real help. You:",
        "option_A": "Be honest about where you are and offer what you can without depleting yourself.",
        "option_B": "Give what you can even if it stretches you somewhat.",
        "option_C": "Decline for now and be specific about when you'd be in a better position to help.",
        "option_D": "Give fully and deal with the personal cost afterward.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "AHB5",
        "trait": "Agreeableness",
        "sub_dimension": "Helping_Behavior",
        "scenario": "When I recognize that my help is enabling a pattern someone should address themselves, I:",
        "option_A": "Shift from helping to coaching — I adjust how I support them to build their independence.",
        "option_B": "Help again but name the pattern so they're aware of it.",
        "option_C": "Continue helping but feel conflicted about whether I'm doing the right thing.",
        "option_D": "Keep helping fully — stopping feels harmful even when I can see the enabling dynamic.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # =========================================================
    # NEUROTICISM — 5 sub-dimensions × 5 questions = 25
    # =========================================================

    # --- Neuroticism / Stress_Response ---
    {
        "id": "NSR1",
        "trait": "Neuroticism",
        "sub_dimension": "Stress_Response",
        "scenario": "You have three things due on the same day and one just got more complicated. Your first internal reaction is:",
        "option_A": "It registers as information — I move straight into an adjusted plan.",
        "option_B": "I note it's more than I'd like and start figuring out what needs to shift.",
        "option_C": "I feel a pull toward worst-case scenarios before I've assessed what's actually changed.",
        "option_D": "Something close to panic that I have to actively work to manage.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NSR2",
        "trait": "Neuroticism",
        "sub_dimension": "Stress_Response",
        "scenario": "You are in a period of sustained pressure — weeks, not days — with no clear end point. Your baseline:",
        "option_A": "Sustained pressure sharpens me rather than depletes me.",
        "option_B": "I'm more tired than usual but my functioning stays relatively consistent.",
        "option_C": "I feel it accumulating but can usually identify what's happening and compensate.",
        "option_D": "Shifts noticeably — I become more reactive, more irritable, and less able to absorb new problems.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NSR3",
        "trait": "Neuroticism",
        "sub_dimension": "Stress_Response",
        "scenario": "I handle stress without it significantly affecting my mood or daily output.",
        "option_A": "Almost always — I stay composed under pressure in a way others often comment on.",
        "option_B": "Usually — I handle most stressors without much visible impact.",
        "option_C": "Sometimes — I manage okay but stress definitely shows.",
        "option_D": "Rarely — stress visibly affects my mood and productivity.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "NSR4",
        "trait": "Neuroticism",
        "sub_dimension": "Stress_Response",
        "scenario": "You're in a conversation that starts escalating unexpectedly — voices rise, tone shifts. Internally:",
        "option_A": "The escalation doesn't significantly change how I operate — I respond to content more than tone.",
        "option_B": "I notice the change and adjust without much internal disruption.",
        "option_C": "I feel the shift and it affects my thinking — I become less fluid than I'd like.",
        "option_D": "Something activates almost immediately — heart rate, tightening — that I manage even while responding.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NSR5",
        "trait": "Neuroticism",
        "sub_dimension": "Stress_Response",
        "scenario": "A week of high stress ends and you finally have downtime. The transition feels:",
        "option_A": "Easy — I transition quickly into rest and don't carry stress into it.",
        "option_B": "Smooth — by end of the first calm day I feel genuinely recovered.",
        "option_C": "Gradual — the first day brings some release but it takes time to fully settle.",
        "option_D": "Slow — my body and mind stay activated and I don't come down quickly.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Neuroticism / Anxiety_Worry ---
    {
        "id": "NAW1",
        "trait": "Neuroticism",
        "sub_dimension": "Anxiety_Worry",
        "scenario": "You send an important message and don't get a reply for longer than expected. Your mind:",
        "option_A": "Doesn't track response timing closely enough for a delay to feel meaningful.",
        "option_B": "Registers it once and gets on with other things.",
        "option_C": "Notices the delay and returns to it with mild unease.",
        "option_D": "Generates unfavorable explanations for the silence before you consciously decide to.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NAW2",
        "trait": "Neuroticism",
        "sub_dimension": "Anxiety_Worry",
        "scenario": "You have nothing urgent to worry about right now. That feels:",
        "option_A": "Normal — most of life is low-pressure and I don't experience calm as unusual.",
        "option_B": "Genuinely pleasant — I inhabit the ease without attaching a caveat.",
        "option_C": "A little unnatural — I notice the absence of pressure more than I enjoy it.",
        "option_D": "Suspicious — when things are quiet I find myself scanning for what might be about to go wrong.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NAW3",
        "trait": "Neuroticism",
        "sub_dimension": "Anxiety_Worry",
        "scenario": "When I recognize that something is outside my control, I typically:",
        "option_A": "Let it go genuinely — once I've accepted something is uncontrollable I don't keep returning to it.",
        "option_B": "Mostly release it, with occasional returns I can usually redirect.",
        "option_C": "Try not to dwell but find myself worrying about it anyway.",
        "option_D": "Continue worrying about it even when I know dwelling won't change anything.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "NAW4",
        "trait": "Neuroticism",
        "sub_dimension": "Anxiety_Worry",
        "scenario": "You're trying to sleep but your mind keeps returning to something unresolved from the day. What happens?",
        "option_A": "I don't carry the day into sleep much — once I'm in bed earlier events don't follow me.",
        "option_B": "I process it briefly and find I can put it down when sleep is the priority.",
        "option_C": "I think about it longer than I'd like before managing to set it aside.",
        "option_D": "My mind replays it in loops — I can interrupt it briefly but it keeps coming back.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NAW5",
        "trait": "Neuroticism",
        "sub_dimension": "Anxiety_Worry",
        "scenario": "Something small goes wrong and you catch yourself imagining how it could compound into something much larger. You:",
        "option_A": "Don't tend to project forward — you deal with what's actually in front of you.",
        "option_B": "Catch the spiral early and find it fairly easy to return to what's actually true.",
        "option_C": "Notice you've projected forward and consciously redirect — it takes some effort.",
        "option_D": "Feel the imagined chain of consequences emotionally before you even stop yourself.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Neuroticism / Emotional_Stability ---
    {
        "id": "NES1",
        "trait": "Neuroticism",
        "sub_dimension": "Emotional_Stability",
        "scenario": "You receive sharp public criticism for something you put real effort into. The rest of the day still has demands. What happens?",
        "option_A": "The criticism registers but doesn't significantly alter my state — I move into the next thing.",
        "option_B": "I process it during a break and show up to the next thing without carrying it visibly.",
        "option_C": "I feel the hit and it takes an hour or two before I can genuinely re-engage.",
        "option_D": "The criticism stays active — it affects my concentration and mood for the rest of the day.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NES2",
        "trait": "Neuroticism",
        "sub_dimension": "Emotional_Stability",
        "scenario": "When the people around me are stressed or tense, my own emotional state:",
        "option_A": "Stays largely independent — I can be present in a charged environment without absorbing it.",
        "option_B": "Remains mostly stable with minor fluctuations.",
        "option_C": "Is somewhat affected even when I know the source isn't mine.",
        "option_D": "Shifts noticeably — I absorb the emotional atmosphere of a room.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NES3",
        "trait": "Neuroticism",
        "sub_dimension": "Emotional_Stability",
        "scenario": "I maintain a consistent emotional baseline even when things go wrong.",
        "option_A": "Almost always — my emotional baseline is robust and hard to move significantly.",
        "option_B": "Usually — I feel things but they don't dramatically alter my baseline.",
        "option_C": "Sometimes — I manage okay but difficult periods show up in my mood.",
        "option_D": "Rarely — setbacks typically shift my baseline noticeably.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "NES4",
        "trait": "Neuroticism",
        "sub_dimension": "Emotional_Stability",
        "scenario": "You have a strong emotional reaction — frustration, hurt — in a moment that requires you to keep functioning. What happens?",
        "option_A": "I compartmentalize almost automatically — the processing happens later without affecting performance.",
        "option_B": "I can hold both — I feel what I feel and still operate without one undermining the other.",
        "option_C": "I stay functional but the emotion runs in the background and surfaces in small ways.",
        "option_D": "The emotion and the functioning compete — holding both at once is genuinely difficult.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NES5",
        "trait": "Neuroticism",
        "sub_dimension": "Emotional_Stability",
        "scenario": "A streak of bad days — nothing catastrophic, just sustained small frustrations — affects your emotional baseline:",
        "option_A": "Barely — I experience each day fairly independently and streaks don't compound noticeably.",
        "option_B": "Mildly — I notice the pattern and give myself space without letting it define my state.",
        "option_C": "Noticeably — I feel it building and try to manage it but the sustained nature wears on me.",
        "option_D": "Significantly — accumulation gets to me and it becomes harder to stay even-keeled.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Neuroticism / Self_Doubt ---
    {
        "id": "NSD1",
        "trait": "Neuroticism",
        "sub_dimension": "Self_Doubt",
        "scenario": "You've just completed something you worked hard on. Before anyone sees it, you:",
        "option_A": "Feel done — I assess it once, feel satisfied, and move on without second-guessing.",
        "option_B": "Feel satisfied and notice any critical voice without giving it much weight.",
        "option_C": "Feel good briefly, then a low hum of uncertainty sets in about whether it's as strong as I thought.",
        "option_D": "Find fault almost immediately — a critical inner voice activates that I can't fully silence.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NSD2",
        "trait": "Neuroticism",
        "sub_dimension": "Self_Doubt",
        "scenario": "Someone compliments your work or judgment. You:",
        "option_A": "Believe they mean it and don't complicate it further.",
        "option_B": "Take it in genuinely and let it update how you see the work.",
        "option_C": "Appreciate it but hold it lightly — you're not fully convinced by external validation alone.",
        "option_D": "Discount it — they're being kind, or they haven't seen the flaws, or they're not qualified to judge.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NSD3",
        "trait": "Neuroticism",
        "sub_dimension": "Self_Doubt",
        "scenario": "I feel confident in my abilities and judgments most of the time.",
        "option_A": "Almost always — confidence is my default state and doubt is the exception.",
        "option_B": "Usually — I feel capable most of the time with occasional dips.",
        "option_C": "Sometimes — I have confident periods but they're interrupted by doubt.",
        "option_D": "Rarely — self-doubt is a consistent presence that affects many decisions.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "NSD4",
        "trait": "Neuroticism",
        "sub_dimension": "Self_Doubt",
        "scenario": "You are in a room with people you perceive as more experienced or credentialed. You:",
        "option_A": "Contribute based on what you have to offer — the relative capability of the room doesn't change how you show up.",
        "option_B": "Engage relatively normally — you might be more curious but not significantly more cautious.",
        "option_C": "Are aware of the gap and become more selective about when you speak up.",
        "option_D": "Become quieter and more deferential — you hold back things you'd say in a different room.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NSD5",
        "trait": "Neuroticism",
        "sub_dimension": "Self_Doubt",
        "scenario": "Someone disagrees with your position firmly. Your confidence in what you said:",
        "option_A": "Stays tied to the quality of your reasoning, not to whether others agree.",
        "option_B": "You feel a pull toward doubt but hold your position until you've heard something that actually challenges it.",
        "option_C": "Wobbles somewhat — you find yourself reviewing your reasoning under the social pressure.",
        "option_D": "Drops noticeably — disagreement makes you question whether you were right before you've even heard the argument.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },

    # --- Neuroticism / Reaction_to_Failure ---
    {
        "id": "NRF1",
        "trait": "Neuroticism",
        "sub_dimension": "Reaction_to_Failure",
        "scenario": "You fail at something you genuinely cared about. In the first hour:",
        "option_A": "I feel the loss and fairly quickly shift into thinking about what comes next.",
        "option_B": "I feel the disappointment clearly and also find myself moving toward what happened and why.",
        "option_C": "I feel it sharply and need time away from people before I can begin to process it.",
        "option_D": "Something collapses internally — the failure registers as something about me, not just an outcome.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NRF2",
        "trait": "Neuroticism",
        "sub_dimension": "Reaction_to_Failure",
        "scenario": "After a significant failure, how long does it continue to affect your day-to-day mood?",
        "option_A": "The acute feeling passes within hours — by the next day I'm operating normally.",
        "option_B": "A day or two of lower energy, then I'm genuinely back without much residue.",
        "option_C": "Several days of noticeably reduced motivation before returning to baseline.",
        "option_D": "Weeks — it runs as a background signal that colors how I show up.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NRF3",
        "trait": "Neuroticism",
        "sub_dimension": "Reaction_to_Failure",
        "scenario": "I treat failure primarily as information that helps me improve.",
        "option_A": "Almost always — I genuinely experience failure as data more than as a verdict on me.",
        "option_B": "Usually — I feel the sting but move into learning mode within a day or two.",
        "option_C": "Sometimes — I can reach that framing eventually but not quickly.",
        "option_D": "Rarely — failure feels personal and it takes a long time before I can see it analytically.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": False,
    },
    {
        "id": "NRF4",
        "trait": "Neuroticism",
        "sub_dimension": "Reaction_to_Failure",
        "scenario": "The possibility of failing affects whether I attempt things.",
        "option_A": "Very little — whether I might fail doesn't feature much in whether I decide to try.",
        "option_B": "Mildly — I occasionally hesitate but it doesn't systematically narrow what I pursue.",
        "option_C": "Somewhat — I'm more selective than I'd ideally like about what I go after.",
        "option_D": "Significantly — there are things I don't attempt because the risk of failing feels too high.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
    {
        "id": "NRF5",
        "trait": "Neuroticism",
        "sub_dimension": "Reaction_to_Failure",
        "scenario": "After a failure, the internal conversation that follows is:",
        "option_A": "Fairly matter-of-fact — I assess what happened without the inner dialogue getting emotionally charged.",
        "option_B": "Held with accountability but without brutality — I'm honest without being harsh.",
        "option_C": "More critical than I'd like — I know I'm being hard on myself but can't fully soften it.",
        "option_D": "Harsh — the voice I use with myself is harsher than anything I'd say to someone I care about.",
        "weight_A": 1.0,
        "weight_B": 0.75,
        "weight_C": 0.5,
        "weight_D": 0.25,
        "reverse": True,
    },
]

SUB_DIMENSIONS = {
    "Openness/Curiosity": ["OC1", "OC2", "OC3", "OC4", "OC5"],
    "Openness/Imagination": ["OI1", "OI2", "OI3", "OI4", "OI5"],
    "Openness/Intellectual_Exploration": ["OIE1", "OIE2", "OIE3", "OIE4", "OIE5"],
    "Openness/Preference_for_Novelty": ["OPN1", "OPN2", "OPN3", "OPN4", "OPN5"],
    "Openness/Creativity": ["OCR1", "OCR2", "OCR3", "OCR4", "OCR5"],

    "Conscientiousness/Planning": ["CP1", "CP2", "CP3", "CP4", "CP5"],
    "Conscientiousness/Discipline": ["CD1", "CD2", "CD3", "CD4", "CD5"],
    "Conscientiousness/Responsibility": ["CR1", "CR2", "CR3", "CR4", "CR5"],
    "Conscientiousness/Goal_Orientation": ["CGO1", "CGO2", "CGO3", "CGO4", "CGO5"],
    "Conscientiousness/Time_Management": ["CTM1", "CTM2", "CTM3", "CTM4", "CTM5"],

    "Extraversion/Social_Energy": ["ESE1", "ESE2", "ESE3", "ESE4", "ESE5"],
    "Extraversion/Assertiveness": ["EAS1", "EAS2", "EAS3", "EAS4", "EAS5"],
    "Extraversion/Expressiveness": ["EEX1", "EEX2", "EEX3", "EEX4", "EEX5"],
    "Extraversion/Social_Risk_Taking": ["ESRT1", "ESRT2", "ESRT3", "ESRT4", "ESRT5"],
    "Extraversion/Leadership_Initiative": ["ELI1", "ELI2", "ELI3", "ELI4", "ELI5"],

    "Agreeableness/Empathy": ["AEM1", "AEM2", "AEM3", "AEM4", "AEM5"],
    "Agreeableness/Cooperation": ["ACO1", "ACO2", "ACO3", "ACO4", "ACO5"],
    "Agreeableness/Trust": ["ATR1", "ATR2", "ATR3", "ATR4", "ATR5"],
    "Agreeableness/Conflict_Handling": ["ACH1", "ACH2", "ACH3", "ACH4", "ACH5"],
    "Agreeableness/Helping_Behavior": ["AHB1", "AHB2", "AHB3", "AHB4", "AHB5"],

    "Neuroticism/Stress_Response": ["NSR1", "NSR2", "NSR3", "NSR4", "NSR5"],
    "Neuroticism/Anxiety_Worry": ["NAW1", "NAW2", "NAW3", "NAW4", "NAW5"],
    "Neuroticism/Emotional_Stability": ["NES1", "NES2", "NES3", "NES4", "NES5"],
    "Neuroticism/Self_Doubt": ["NSD1", "NSD2", "NSD3", "NSD4", "NSD5"],
    "Neuroticism/Reaction_to_Failure": ["NRF1", "NRF2", "NRF3", "NRF4", "NRF5"],
}

TRAITS = [
    "Openness",
    "Conscientiousness",
    "Extraversion",
    "Agreeableness",
    "Neuroticism",
]